### ISSUE TITLE
Add error checking for valid Swift input

### ISSUE THREAD

**Issue by mohsen1** [shift-js/shift-js#275]
```
let a:String = 1;
```

is transpired to `var a = 1;` but it should throw an error

**Comment by ghost** [comment]
It's not yet doing any syntactical checks on the input.  Given the state of Swift, assumption is that most devs might use Xcode for all error checking, then transpile with the CLI.  Still far from being ready for production.  This is on the list.  Thanks.

**Comment by mohsen1** [comment]
Fair enough. :+1:
