### ISSUE TITLE
Operators can get passed as function arguments 

### ISSUE THREAD

**Issue by mohsen1** [shift-js/shift-js#276]
``` swift
let arr = [5, 6, 9, 10]

let sum = arr.reduce(0, combine: +);
```

Why Swift decided this is a good feature is beyond me! :disappointed: :gun:

**Comment by mohsen1** [comment]
This is part of [Swift block syntax](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html)

Other examples:

``` swift
let arr = [5, 6, 9, 10]

let sorted = arr.sort() { $0 > $1 }
// or
arr.sort { $0 > $1 }
// or
arr.sort(>)
```

**Comment by dchrch** [comment]
Thanks for pointing that out.  Block syntax and native methods are at the top of our todo list. :smile:

**Comment by ghost** [comment]
I updated the code to reflect changes that allow the first issue post to be handled correctly, as far as the lexer goes, parser and generators updates will come later, but the tokens will now be correctly generated. As far as the second issue goes, block scoping will come later. Thank you for pointing these issues out.
