### ISSUE TITLE
Shift AST

### ISSUE THREAD

**Issue by jsoverson** [shift-js/shift-js#284]
Not sure you came across this before you named the project, but `shift` is the name of [a suite of javascript parsing, codegen, and transformation libraries](http://shift-ast.org/).

Given the nature of the two projects, it may be very confusing for both to be named shift.

**Comment by dchrch** [comment]
We hadn't heard of Shift AST until now.  It looks like an interesting project.  We don't currently plan on changing our project name.  If we come across any confusion between projects, we will make sure to be clear about the distinction.
